version: '3'

services:
  cryptpythoncode:
    image: cryptpythoncode
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./result:/app/dist
    command: bash ./docker_entry.sh
    tty: true