version: '2.3'

services:
  cryptpythoncode:
    image: cryptpythoncode
    runtime: nvidia
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./result:/app/dist
    tty: true